// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import ()

var ()

// StorerMock is a mock implementation of Storer.
//
//     func TestSomethingThatUsesStorer(t *testing.T) {
//
//         // make and configure a mocked Storer
//         mockedStorer := &StorerMock{
//         }
//
//         // TODO: use mockedStorer in code that requires Storer
//         //       and then make assertions.
//
//     }
type StorerMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
